export const navTabs = [
  'Members',
  'Domains',
  'Hackathon Vault',
  'Projects',
  'Leaderboard',
  'Team Vault',
]

export const teamMembers = [
  {
    name: 'KIRUTHIKA NIMAL G',
    role: 'Captain',
    status: 'Hackathon Mode',
    registerNo: 'NEXA10020501',
    collegeEmail: 'kiruthikanimalg.it25@bitsathy.ac.in',
    personalEmail: 'kiruthikagopi11@gmail.com',
    github: 'https://github.com/kiruthika-nimal',
    linkedin:
      'https://www.linkedin.com/in/kiruthika-nimal-gopi?utm_source=share_via&utm_content=profile&utm_medium=member_android',
    photo: '/photos/kiruthika.jpg',
    skills: ['Agentic AI & LLM', 'DevOps', 'Team Leadership'],
    contributions: 48,
    psWallet: {
      mode: 'Activity Points',
      isActive: true,
      points: 4425,
      groupId: 'A#100205',
      totalGroupPoints: 50185,
      myContribution: 4425,
      contributionShare: 8.8,
      overallRank: 985,
      totalParticipants: 1789,
    },
  },
  {
    name: 'SHAMIKSHA A',
    role: 'Vice Captain',
    status: 'Coding',
    registerNo: 'NEXA10020502',
    collegeEmail: 'shamikshaa.it25@bitsathy.ac.in',
    personalEmail: 'its.shamiksha.tech@gmail.com',
    github: 'https://github.com/itsshamikshatech-droid',
    linkedin: 'https://www.linkedin.com/in/shamiksha-anandkumar',
    photo: '/photos/shamiksha.jpg',
    skills: ['Agentic AI & LLM', 'Cybersecurity', 'System Design'],
    contributions: 42,
    psWallet: {
      mode: 'Activity Points',
      isActive: true,
      points: 5855,
      groupId: 'A#100205',
      totalGroupPoints: 50185,
      myContribution: 5855,
      contributionShare: 11.7,
      overallRank: 453,
      totalParticipants: 1789,
    },
  },
  {
    name: 'SUSHANTHI P',
    role: 'Team Strategist',
    status: 'In Lab',
    registerNo: 'NEXA10020503',
    collegeEmail: 'sushanthip.it25@bitsathy.ac.in',
    personalEmail: 'Sushanthi736@gmail.com',
    github: 'https://github.com/sush159',
    linkedin: 'https://www.linkedin.com/in/sushanthi-p-634a74381/',
    skills: ['Cybersecurity', 'DevOps', 'Architecture'],
    contributions: 37,
    psWallet: {
      mode: 'Activity Points',
      isActive: true,
      points: 6460,
      groupId: 'A#100205',
      totalGroupPoints: 50185,
      myContribution: 6460,
      contributionShare: 12.9,
      overallRank: 312,
      totalParticipants: 1789,
    },
  },
  {
    name: 'SACHIN AKASH B J',
    role: 'Team Manager',
    status: 'Syncing Releases',
    registerNo: 'NEXA10020504',
    collegeEmail: 'sachinakashbj.it25@bitsathy.ac.in',
    personalEmail: 'Sachinakash2911@gmail.com',
    github: 'https://github.com/sachinakash2911',
    linkedin:
      'https://www.linkedin.com/in/sachin-akash-b-j-a16b75359?utm_source=share_via&utm_content=profile&utm_medium=member_android',
    skills: ['DevOps', 'Cloud', 'Planning'],
    contributions: 35,
    psWallet: {
      mode: 'Activity Points',
      isActive: true,
      points: 5205,
      groupId: 'A#100205',
      totalGroupPoints: 50185,
      myContribution: 5205,
      contributionShare: 10.4,
      overallRank: 674,
      totalParticipants: 1789,
    },
  },
  {
    name: 'ASHMITA M',
    role: 'Member',
    status: 'Security Testing',
    registerNo: 'NEXA10020505',
    collegeEmail: 'ashmitam.it25@bitsathy.ac.in',
    personalEmail: 'ashmitamurugesan35@gmail.com',
    github: 'https://github.com/ashmitamurugesan35-debug/',
    linkedin:
      'https://www.linkedin.com/in/ashmita-murugesan-a22069379?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app',
    skills: ['Cybersecurity', 'Edge AI', 'QA'],
    contributions: 33,
    psWallet: {
      mode: 'Activity Points',
      isActive: true,
      points: 4370,
      groupId: 'A#100205',
      totalGroupPoints: 50185,
      myContribution: 4370,
      contributionShare: 8.7,
      overallRank: 1008,
      totalParticipants: 1789,
    },
  },
  {
    name: 'DHANYAA M R',
    role: 'Member',
    status: 'Model Tuning',
    registerNo: 'NEXA10020506',
    collegeEmail: 'dhanyaamr.it25@bitsathy.ac.in',
    personalEmail: 'dhanyaamr56@gmail.com',
    github: 'https://github.com/dhanyaamr-gif',
    linkedin:
      'https://www.linkedin.com/in/dhanyaa-m-r-0a969137b?utm_source=share_via&utm_content=profile&utm_medium=member_android',
    skills: ['Big Data & ML', 'Cloud', 'Full Stack'],
    contributions: 39,
    psWallet: {
      mode: 'Activity Points',
      isActive: true,
      points: 4930,
      groupId: 'A#100205',
      totalGroupPoints: 50185,
      myContribution: 4930,
      contributionShare: 9.8,
      overallRank: 798,
      totalParticipants: 1789,
    },
  },
  {
    name: 'KAMALESH R S',
    role: 'Member',
    status: 'Inference Build',
    registerNo: 'NEXA10020507',
    collegeEmail: 'kamaleshrs.it25@bitsathy.ac.in',
    personalEmail: 'Kamaleshsamkrish@gmail.com',
    github: 'https://github.com/kamlesh-edge',
    linkedin: 'https://www.linkedin.com/in/kamlesh',
    skills: ['Big Data & ML', 'Edge AI', 'APIs'],
    contributions: 29,
  },
  {
    name: 'PRATIBA M',
    role: 'Member',
    status: 'Cloud Deploy',
    registerNo: 'NEXA10020508',
    collegeEmail: 'pratibam.it25@bitsathy.ac.in',
    personalEmail: 'pratibamahesh49@gmail.com',
    github: 'https://github.com/pratiba-code',
    linkedin: 'https://www.linkedin.com/in/pratiba',
    skills: ['Cloud', 'Full Stack', 'UI Systems'],
    contributions: 31,
    psWallet: {
      mode: 'Activity Points',
      isActive: true,
      points: 5870,
      groupId: 'A#100205',
      totalGroupPoints: 50185,
      myContribution: 5870,
      contributionShare: 11.7,
      overallRank: 447,
      totalParticipants: 1789,
    },
  },
  {
    name: 'SARAN S',
    role: 'Member',
    status: 'Agent Pipeline',
    registerNo: 'NEXA10020509',
    collegeEmail: 'sarans.it25@bitsathy.ac.in',
    personalEmail: 'sarans2223@gmail.com',
    github: 'https://github.com/sarans2223/',
    linkedin:
      'https://www.linkedin.com/in/saran-s-89bb51378?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app',
    skills: ['Agentic AI & LLM', 'Edge AI', 'Prototyping'],
    contributions: 41,
    psWallet: {
      mode: 'Activity Points',
      isActive: true,
      points: 4980,
      groupId: 'A#100205',
      totalGroupPoints: 50185,
      myContribution: 4980,
      contributionShare: 9.9,
      overallRank: 770,
      totalParticipants: 1789,
    },
  },
  {
    name: 'TANYA P S',
    role: 'Member',
    status: 'Frontend Sprint',
    registerNo: 'NEXA10020510',
    collegeEmail: 'tanyaps.it25@bitsathy.ac.in',
    personalEmail: 'tanyaps025@gmail.com',
    github: 'https://github.com/TanyaPS25',
    linkedin:
      'https://www.linkedin.com/in/tanya-ps-8b0770385?utm_source=share_via&utm_content=profile&utm_medium=member_android',
    skills: ['Full Stack', 'Accessibility', 'UX'],
    contributions: 28,
    psWallet: {
      mode: 'Activity Points',
      isActive: true,
      points: 3995,
      groupId: 'A#100205',
      totalGroupPoints: 50185,
      myContribution: 3995,
      contributionShare: 8.0,
      overallRank: 1180,
      totalParticipants: 1789,
    },
  },
]

export const domainMatrix = [
  { domain: 'Agentic AI & LLM', members: ['SARAN S', 'SHAMIKSHA A', 'KIRUTHIKA NIMAL G'] },
  { domain: 'Cybersecurity', members: ['ASHMITA M', 'SUSHANTHI P', 'SHAMIKSHA A'] },
  { domain: 'Big Data & ML', members: ['DHANYAA M R', 'KAMALESH R S'] },
  { domain: 'DevOps', members: ['KIRUTHIKA NIMAL G', 'SACHIN AKASH B J', 'SUSHANTHI P'] },
  { domain: 'Edge AI', members: ['ASHMITA M', 'SARAN S', 'KAMALESH R S'] },
  { domain: 'Cloud', members: ['SACHIN AKASH B J', 'DHANYAA M R', 'PRATIBA M'] },
  { domain: 'Full Stack', members: ['DHANYAA M R', 'PRATIBA M', 'TANYA P S'] },
]

export const hackathonVault = [
  {
    title: 'HACK TO HIRE',
    date: 'Nov 2025',
    description: 'Secured 1st and 3rd place wins across challenge tracks.',
    award: 'Dual Podium Finish',
  },
  {
    title: 'TN SKILLS LEVEL 3',
    date: '2025',
    description: 'Software Testing certification event at Zoho Chennai.',
    award: 'Testing Excellence',
  },
  {
    title: 'SHASTHRA',
    date: '2025',
    description: 'Participated in IIT Madras flagship technical festival.',
    award: 'National Exposure',
  },
  {
    title: 'CIT SPARK SUMMIT',
    date: '2025',
    description: 'Project presentation spotlight by Saran and Ashmita.',
    award: 'Featured Presentation',
  },
  {
    title: 'MULTIVERSE',
    date: '2025',
    description: '30-hour hackathon with Best Special Award and INR 3000 prize.',
    award: 'Best Special Award',
  },
  {
    title: 'NEXTGENNEXUS (IEEE)',
    date: '2025',
    description: 'Placed Top 3 among 100+ competing teams.',
    award: 'Top 3 National Rank',
  },
]

export const projects = [
  {
    title: 'VASA',
    tag: "Women's Empowerment",
    live: '#',
    source: '#',
    progress: 70,
    stage: 'UI Flow Integration',
    owner: 'TANYA P S',
  },
  {
    title: 'Planify',
    tag: 'Smart Education',
    live: '#',
    source: '#',
    progress: 82,
    stage: 'Model + API Testing',
    owner: 'DHANYAA M R',
  },
  {
    title: 'Caterpillar Hackathon Project',
    tag: 'Innovation Sprint',
    live: '#',
    source: '#',
    progress: 79,
    stage: 'Feature Freeze',
    owner: 'SACHIN AKASH B J',
  },
  {
    title: 'Medtrace',
    tag: 'HealthTech',
    live: '#',
    source: '#',
    progress: 91,
    stage: 'Final Validation',
    owner: 'SHAMIKSHA A',
  },
  { title: 'Swayam Lekh', tag: 'AI Scribe', live: '#', source: '#' },
  { title: 'ResQ Vision', tag: 'Safety AI', live: '#', source: '#' },
  { title: 'Sentinal AI', tag: 'Security Intelligence', live: '#', source: '#' },
  { title: 'Civic AI', tag: 'Public Systems', live: '#', source: '#' },
  { title: 'Fairwatt', tag: 'Energy Analytics', live: '#', source: '#' },
  { title: 'Capguard', tag: 'Compliance Guard', live: '#', source: '#' },
]

export const vaultAssets = ['Team Logos', 'PPT Templates', 'Research Papers']
